using System.Text.RegularExpressions;

namespace AgentGuard.Core.Rules;

/// <summary>
/// Fixed pair of generated-file signals (009-generated-file-contamination FR-001, FR-002,
/// research.md §1). Deliberately narrow, mirroring every other pattern-list rule, rather than a
/// general build-artifact/codegen-manifest analyzer (FR-010).
/// </summary>
public static partial class GeneratedFileSignals
{
    /// <summary>Matched against a changed file's path.</summary>
    public static Regex ExtensionPattern => GeneratedFileExtensionPattern();

    /// <summary>Matched against a changed file's new content.</summary>
    public static Regex MarkerPattern => GeneratedFileMarkerPattern();

    [GeneratedRegex(@"(?i)\.(generated\.cs|g\.cs|designer\.cs|pb\.go)$|_pb2\.py$|\.min\.js$")]
    private static partial Regex GeneratedFileExtensionPattern();

    [GeneratedRegex(@"(?i)(auto-generated|do not edit this file|automatically generated)")]
    private static partial Regex GeneratedFileMarkerPattern();
}
